# Generated by Django 4.2 on 2023-05-17 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
                ('fornecedor', models.CharField(max_length=100)),
                ('peca', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('defeito', models.CharField(max_length=100)),
                ('quantidade_total', models.IntegerField()),
                ('aprovados', models.IntegerField()),
                ('rejeitados', models.IntegerField()),
                ('retrabalhados', models.IntegerField()),
                ('operadores', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.CharField(max_length=100, null=True)),
                ('hora_fim', models.CharField(max_length=100, null=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.registro')),
            ],
        ),
    ]
