# Generated by Django 4.2 on 2023-08-16 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_mensais', models.PositiveIntegerField(default=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
                ('fornecedor', models.CharField(max_length=100)),
                ('peca', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('defeito', models.CharField(max_length=100)),
                ('quantidade_total', models.IntegerField()),
                ('aprovados', models.IntegerField()),
                ('rejeitados', models.IntegerField()),
                ('retrabalhados', models.IntegerField()),
                ('data_fabricacao', models.CharField(max_length=100)),
                ('horario_inicio_1', models.TimeField(default='00:00')),
                ('horario_fim_1', models.TimeField(default='00:00')),
                ('horario_inicio_2', models.TimeField(default='00:00', null=True)),
                ('horario_fim_2', models.TimeField(default='00:00', null=True)),
                ('horario_inicio_3', models.TimeField(default='00:00', null=True)),
                ('horario_fim_3', models.TimeField(default='00:00', null=True)),
                ('horario_inicio_4', models.TimeField(default='00:00', null=True)),
                ('horario_fim_4', models.TimeField(default='00:00', null=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_criados', to=settings.AUTH_USER_MODEL)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.local')),
                ('operador_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_operador_1', to=settings.AUTH_USER_MODEL)),
                ('operador_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_operador_2', to=settings.AUTH_USER_MODEL)),
                ('operador_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_operador_3', to=settings.AUTH_USER_MODEL)),
                ('operador_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_operador_4', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
