# Generated by Django 4.2 on 2023-08-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='produtividade',
            field=models.FloatField(default=0.0),
        ),
    ]
