# Generated by Django 4.2 on 2023-04-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_registro_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='hora',
        ),
        migrations.AddField(
            model_name='registro',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='hora_saida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='data',
            field=models.CharField(max_length=100),
        ),
    ]
