# Generated by Django 4.2 on 2023-08-17 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_usuario_produtividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='horario_fim_2',
            field=models.TimeField(blank=True, default='00:00', null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='horario_fim_3',
            field=models.TimeField(blank=True, default='00:00', null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='horario_fim_4',
            field=models.TimeField(blank=True, default='00:00', null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='horario_inicio_2',
            field=models.TimeField(blank=True, default='00:00', null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='horario_inicio_3',
            field=models.TimeField(blank=True, default='00:00', null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='horario_inicio_4',
            field=models.TimeField(blank=True, default='00:00', null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='operador_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_operador_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registro',
            name='operador_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_operador_3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registro',
            name='operador_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_operador_4', to=settings.AUTH_USER_MODEL),
        ),
    ]
