# Generated by Django 4.2 on 2023-08-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_registro_horario_fim_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='produtividade',
            new_name='produtividade_anterior',
        ),
        migrations.AddField(
            model_name='usuario',
            name='produtividade_anual',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='produtividade_diaria',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='produtividade_mensal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='registro',
            name='data',
            field=models.DateField(),
        ),
    ]
