# Generated by Django 4.2 on 2023-08-21 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_produtividade_usuario_produtividade_anterior_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsMeses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('ano', models.PositiveIntegerField()),
                ('horas_mensais', models.PositiveIntegerField()),
                ('produtividade_diaria', models.FloatField()),
                ('produtividade_mensal', models.FloatField()),
                ('produtividade_anual', models.FloatField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
